services:
  api:
    build: .
    container_name: contratacao-api
    command: uvicorn api.main:create_app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENABLE_METRICS=true
      - PYTHONUNBUFFERED=1
    healthcheck:
      # Dica: certifique-se de ter 'curl' ou 'wget' na imagem. Se não tiver, remova o healthcheck ou instale uma das ferramentas.
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ || curl -fsS http://localhost:8000/"]
      interval: 15s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
    volumes:
      - prom-data:/prometheus
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    # (sem depends_on) – Prometheus pode iniciar sem a API; ele vai tentar coletar e, quando a API subir, começa a ter sucesso.

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      # (opcional) - api
      # - api

volumes:
  prom-data:
  grafana-data:
